### ISSUE TITLE
项目情况咨询

### ISSUE THREAD

**Issue by Leo-zhanglj** [doncat99/zvt#1]
作者您好，
想问一下，目前的程序默认还是使用原有zvt的sqlite3吗，还是已经默认使用pg了。使用作者的程序能直接使用原有zvt的数据库内的数据吗？

**Comment by doncat99** [comment]
> 作者您好， 想问一下，目前的程序默认还是使用原有zvt的sqlite3吗，还是已经默认使用pg了。使用作者的程序能直接使用原有zvt的数据库内的数据吗？

可以参考这个项目：https://github.com/doncat99/FinanceCenter
里面有更详细说明，默认换了pg，三方数据源插件逻辑也进行了解耦。

**Comment by doncat99** [comment]
至于数据源，如您关心的国内数据，我增加了baostock数据源支持，可以拉取90年开始的全量数据，我也对数据格式进行一定的修正，建议重新拉取。项目采用了异步多进程库（https://github.com/omnilib/aiomultiprocess），应该不会耗时太久。
